(package-initialize)

(add-to-list 'load-path "~/.emacs.d/lisp/")

(require 'init-func)
(require 'init-packages)
(require 'init-ui)
(require 'init-better-defaults)
(require 'init-org)
(require 'init-keybindings)
(require 'init-python)
(require 'init-evil)
(require 'init-yasnippet)
(require 'init-elpy)
(require 'init-flycheck)
(require 'init-py-autopep8)
(require 'init-evil-leader)
(require 'init-term-mode)
(require 'init-pomodoro)
(require 'init-window-numbering)
(require 'init-powerline)
(require 'init-evil-surround)
(require 'init-evil-nerd-commenter)
(require 'init-auto-save)
(require 'init-ruby)
(require 'init-lsp)
(require 'init-web)

(setq custom-file (expand-file-name "lisp/custom.el" user-emacs-directory))

(load-file custom-file)
